"""
Children Service Module
Contains all business logic for children management using PostgreSQL.
Handles child profile storage, management, and statistics with S3 for images.
"""
import base64
import uuid
from datetime import datetime
from typing import Dict, Any, List, Optional
from fastapi import HTTPException
from sqlalchemy import select, update, delete, func
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from src.db.models import User, Child
from src.children.schema import Child as ChildSchema, ChildResponse
from src.common_function.storage_s3_service import S3StorageService
from src.core.config import settings


class ChildrenService:
    """Child service using PostgreSQL instead of Firestore, S3 for media storage"""
    
    def __init__(self):
        self._storage_service = None
    
    @property
    def storage_service(self):
        """Lazy initialization of S3 storage service"""
        if self._storage_service is None:
            self._storage_service = S3StorageService()
        return self._storage_service
    
    async def _get_user_id_from_firebase_id(self, db: AsyncSession, firebase_user_id: str) -> Optional[int]:
        """Helper to convert firebase_user_id (string) to integer user_id, auto-creating if needed"""
        try:
            # Try to get existing user
            stmt = select(User.user_id).where(User.firebase_user_id == firebase_user_id)
            result = await db.execute(stmt)
            user_id = result.scalar_one_or_none()
            
            if user_id:
                return user_id
            
            # User doesn't exist - auto-create minimal user
            from src.user.service_pg import UserServicePostgreSQL
            user_service = UserServicePostgreSQL()
            user = await user_service.get_or_create_minimal_user(db, firebase_user_id)
            return user.user_id
            
        except Exception as e:
            print(f"❌ Error getting/creating user_id from firebase_user_id: {str(e)}")
            return None
    
    async def create_child(
        self,
        db: AsyncSession,
        user_id: int,  # Integer user_id (FK to user.user_id)
        name: str,
        age: int,
        interests: List[str],
        image_base64: Optional[str] = None,
        avatar_seed: Optional[str] = None,
        avatar_style: str = "avataaars",
        system_prompt: Optional[str] = None
    ) -> ChildSchema:
        """Create a new child profile for a parent"""
        try:
            # Verify user exists
            stmt = select(User).where(User.user_id == user_id)
            result = await db.execute(stmt)
            user = result.scalar_one_or_none()
            if not user:
                raise HTTPException(status_code=404, detail=f"User with user_id={user_id} not found in database")
            
            # Handle image upload if provided
            image_url = None
            if image_base64:
                try:
                    image_data = base64.b64decode(image_base64)
                    # Use user's firebase_user_id for S3 path (will add child_id after creation)
                    image_url = await self.storage_service.upload_user_image(image_data, f"{user.firebase_user_id}/child_temp")
                    print(f"✅ Child profile image uploaded to S3: {image_url}")
                except Exception as e:
                    print(f"⚠️ Failed to upload child profile image: {str(e)}")
            
            # Generate personalized system prompt if not provided
            if not system_prompt:
                system_prompt = self._generate_personalized_prompt(name, age, interests)
            
            # Create child record with INTEGER user_id (child_id will auto-increment)
            child = Child(
                # child_id is auto-generated by database (BIGINT autoincrement)
                user_id=user_id,  # Use integer user_id FK
                name=name,
                age=age,
                interests=interests or [],
                image_url=image_url,
                child_prompt=system_prompt,  # Database field is 'child_prompt' not 'system_prompt'
                is_active=True
            )
            
            db.add(child)
            await db.flush()  # Flush to get the auto-generated child_id
            await db.refresh(child)  # Refresh to get all auto-generated values
            
            # Capture ALL attributes immediately after refresh to avoid lazy loading after commit
            # Note: Database schema only has these fields (no avatar_seed, avatar_style, avatar_url)
            child_id = child.child_id
            child_name = child.name
            child_age = child.age
            child_interests = child.interests
            child_image_url = child.image_url
            child_prompt = child.child_prompt  # Database field name
            child_voice_clone_id = child.voice_clone_id
            child_is_active = child.is_active
            child_created_at = child.created_at.isoformat() if child.created_at else None
            child_updated_at = child.updated_at.isoformat() if child.updated_at else None
            
            print(f"✅ Child created with child_id={child_id}")
            
            # Update parent's children_count and set as default if first child
            stmt = select(User).where(User.user_id == user_id)
            result = await db.execute(stmt)
            user = result.scalar_one_or_none()
            
            if user:
                children_count = user.children_count + 1
                update_data = {
                    'children_count': children_count,
                    'updated_at': datetime.utcnow()
                }
                
                # Set as default if this is the first child
                if children_count == 1 or not user.default_child_id:
                    update_data['default_child_id'] = child_id
                
                stmt = (
                    update(User)
                    .where(User.user_id == user_id)
                    .values(**update_data)
                )
                await db.execute(stmt)
            
            await db.commit()
            
            print(f"✅ Child profile created in PostgreSQL: child_id={child_id} for user_id={user_id}")
            
            return ChildSchema(
                child_id=child_id,
                name=child_name,
                age=child_age,
                interests=child_interests,
                image_url=child_image_url,
                avatar_seed=avatar_seed,  # Return input params (not in DB)
                avatar_style=avatar_style,  # Return input params (not in DB)
                avatar_url=None,  # Not stored in database
                system_prompt=child_prompt,  # Map child_prompt back to system_prompt for API
                voice_clone_id=child_voice_clone_id,
                is_active=child_is_active,
                created_at=child_created_at,
                updated_at=child_updated_at
            )
            
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to create child profile: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to create child profile: {str(e)}")
    
    async def get_child(
        self,
        db: AsyncSession,
        user_id: str,  # firebase_user_id (string)
        child_id: int
    ) -> Optional[ChildSchema]:
        """Get a specific child profile"""
        try:
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                return None
            
            stmt = (
                select(Child)
                .where(Child.user_id == integer_user_id)
                .where(Child.child_id == child_id)
                .where(Child.is_active == True)
            )
            
            result = await db.execute(stmt)
            child = result.scalar_one_or_none()
            
            if not child:
                return None
            
            return ChildSchema(
                child_id=child.child_id,
                name=child.name,
                age=child.age,
                interests=child.interests,
                image_url=child.image_url,
                avatar_seed=None,  # Not stored in database
                avatar_style=None,  # Not stored in database
                avatar_url=None,  # Not stored in database
                system_prompt=child.child_prompt,  # Map child_prompt to system_prompt
                voice_clone_id=child.voice_clone_id,
                is_active=child.is_active,
                created_at=child.created_at.isoformat() if child.created_at else None,
                updated_at=child.updated_at.isoformat() if child.updated_at else None
            )
            
        except Exception as e:
            print(f"❌ Error getting child profile: {str(e)}")
            return None
    
    async def get_all_children(
        self,
        db: AsyncSession,
        user_id: str,  # firebase_user_id (string)
        include_inactive: bool = False
    ) -> List[ChildSchema]:
        """Get all children for a parent"""
        try:
            # Convert firebase_user_id to integer user_id
            print(f"🔍 get_all_children: Looking up firebase_user_id={user_id}")
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            print(f"🔍 get_all_children: Converted to integer user_id={integer_user_id}")
            if not integer_user_id:
                print(f"❌ get_all_children: No user_id found for firebase_user_id={user_id}")
                return []
            
            stmt = (
                select(Child)
                .where(Child.user_id == integer_user_id)
                .order_by(Child.created_at.desc())
            )
            
            if not include_inactive:
                stmt = stmt.where(Child.is_active == True)
            
            print(f"🔍 get_all_children: Executing query for user_id={integer_user_id}, include_inactive={include_inactive}")
            result = await db.execute(stmt)
            children = result.scalars().all()
            print(f"🔍 get_all_children: Found {len(children)} children")
            
            return [
                ChildSchema(
                    child_id=child.child_id,
                    name=child.name,
                    age=child.age,
                    interests=child.interests,
                    image_url=child.image_url,
                    avatar_seed=None,  # Not stored in database
                    avatar_style=None,  # Not stored in database
                    avatar_url=None,  # Not stored in database
                    system_prompt=child.child_prompt,  # Map child_prompt to system_prompt
                    voice_clone_id=child.voice_clone_id,
                    is_active=child.is_active,
                    created_at=child.created_at.isoformat() if child.created_at else None,
                    updated_at=child.updated_at.isoformat() if child.updated_at else None
                )
                for child in children
            ]
            
        except Exception as e:
            print(f"❌ Error getting children: {str(e)}")
            return []
    
    async def update_child(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int,
        name: Optional[str] = None,
        age: Optional[int] = None,
        interests: Optional[List[str]] = None,
        image_base64: Optional[str] = None,
        avatar_seed: Optional[str] = None,
        avatar_style: Optional[str] = None,
        system_prompt: Optional[str] = None
    ) -> Optional[ChildSchema]:
        """Update a child profile"""
        try:
            # Get existing child
            existing_child = await self.get_child(db, user_id, child_id)
            if not existing_child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                raise HTTPException(status_code=404, detail="User not found")
            
            # Prepare updates
            update_data = {'updated_at': datetime.utcnow()}
            
            if name is not None:
                update_data['name'] = name
            if age is not None:
                update_data['age'] = age
            if interests is not None:
                update_data['interests'] = interests
            # avatar_seed and avatar_style are not in database schema - ignore them
            if system_prompt is not None:
                update_data['child_prompt'] = system_prompt  # Database field is child_prompt
            
            # Handle image upload
            if image_base64:
                try:
                    image_data = base64.b64decode(image_base64)
                    image_url = await self.storage_service.upload_user_image(image_data, f"{user_id}/{child_id}")
                    update_data['image_url'] = image_url
                    print(f"✅ Child profile image updated on S3: {image_url}")
                except Exception as e:
                    print(f"⚠️ Failed to upload child profile image: {str(e)}")
            
            # Regenerate system prompt if child info changed
            if (name or age or interests) and system_prompt is None:
                final_name = name if name else existing_child.name
                final_age = age if age else existing_child.age
                final_interests = interests if interests else existing_child.interests
                update_data['child_prompt'] = self._generate_personalized_prompt(final_name, final_age, final_interests)
            
            # Update in database
            stmt = (
                update(Child)
                .where(Child.user_id == integer_user_id)
                .where(Child.child_id == child_id)
                .values(**update_data)
            )
            
            await db.execute(stmt)
            await db.commit()
            
            print(f"✅ Child profile updated in PostgreSQL: {child_id}")
            
            # Return updated child
            return await self.get_child(db, user_id, child_id)
            
        except HTTPException:
            raise
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to update child profile: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to update child profile: {str(e)}")
    
    async def delete_child(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int
    ) -> bool:
        """Soft delete a child profile"""
        try:
            # Verify child exists
            child = await self.get_child(db, user_id, child_id)
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                raise HTTPException(status_code=404, detail="User not found")
            
            # Soft delete
            stmt = (
                update(Child)
                .where(Child.user_id == integer_user_id)
                .where(Child.child_id == child_id)
                .values(is_active=False, updated_at=datetime.utcnow())
            )
            
            await db.execute(stmt)
            
            # Update parent's children_count and default_child_id if needed
            user_stmt = select(User).where(User.user_id == integer_user_id)
            result = await db.execute(user_stmt)
            user = result.scalar_one_or_none()
            
            if user:
                children_count = max(0, user.children_count - 1)
                update_user_data = {
                    'children_count': children_count,
                    'updated_at': datetime.utcnow()
                }
                
                # If deleting the default child, find another active child
                if user.default_child_id == child_id:
                    active_children = await self.get_all_children(db, user_id, include_inactive=False)
                    update_user_data['default_child_id'] = active_children[0].child_id if active_children else None
                
                stmt = (
                    update(User)
                    .where(User.user_id == integer_user_id)
                    .values(**update_user_data)
                )
                await db.execute(stmt)
            
            await db.commit()
            
            print(f"✅ Child profile deleted (soft) in PostgreSQL: {child_id}")
            return True
            
        except HTTPException:
            raise
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to delete child profile: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to delete child profile: {str(e)}")
    
    async def set_default_child(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int
    ) -> bool:
        """Set a child as the default/selected child for a parent"""
        try:
            # Verify child exists and is active
            child = await self.get_child(db, user_id, child_id)
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found or inactive")
            
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                raise HTTPException(status_code=404, detail="User not found")
            
            # Update parent's default_child_id
            stmt = (
                update(User)
                .where(User.user_id == integer_user_id)
                .values(default_child_id=child_id, updated_at=datetime.utcnow())
            )
            
            await db.execute(stmt)
            await db.commit()
            
            print(f"✅ Default child set to: {child_id}")
            return True
            
        except HTTPException:
            raise
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to set default child: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to set default child: {str(e)}")
    
    async def get_child_with_stats(
        self,
        db: AsyncSession,
        user_id: str,  # firebase_user_id (string)
        child_id: int
    ) -> Optional[ChildResponse]:
        """Get child profile with additional statistics"""
        try:
            child = await self.get_child(db, user_id, child_id)
            if not child:
                return None
            
            # Convert firebase_user_id to integer user_id for Story query
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                print(f"❌ get_child_with_stats: No user_id found for firebase_user_id={user_id}")
                return None
            
            # Get story count for this child using integer user_id
            from src.db.models import Story
            stmt = select(func.count(Story.story_id)).where(
                Story.user_id == integer_user_id,  # Use integer user_id
                Story.child_id == child_id
            )
            result = await db.execute(stmt)
            story_count = result.scalar() or 0
            
            # Get voice clones count (from voice_clones table if exists)
            # For now, use 0 as placeholder
            voice_clones_count = 0
            
            # Get reference images count (if child has reference images)
            reference_images_count = 0
            
            return ChildResponse(
                child_id=child.child_id,
                name=child.name,
                age=child.age,
                interests=child.interests,
                image_url=child.image_url,
                avatar_seed=child.avatar_seed,
                avatar_style=child.avatar_style,
                avatar_url=child.avatar_url,
                system_prompt=child.system_prompt,
                voice_clone_id=child.voice_clone_id,
                is_active=child.is_active,
                story_count=story_count,
                voice_clones_count=voice_clones_count,
                reference_images_count=reference_images_count,
                created_at=child.created_at,
                updated_at=child.updated_at
            )
            
        except Exception as e:
            print(f"❌ Error getting child with stats: {str(e)}")
            return None
    
    def _generate_personalized_prompt(self, name: str, age: int, interests: List[str]) -> str:
        """Generate a personalized system prompt based on child's profile"""
        interests_str = ", ".join(interests) if interests else "various topics"
        
        age_appropriate_language = {
            range(3, 6): "very simple words and short sentences",
            range(6, 9): "simple language with some new vocabulary",
            range(9, 13): "age-appropriate language with educational elements"
        }
        
        language_level = "simple, engaging language"
        for age_range, description in age_appropriate_language.items():
            if age in age_range:
                language_level = description
                break
        
        personalized_prompt = f"""You are a creative children's storyteller creating stories for {name}, who is {age} years old and loves {interests_str}.

Create engaging, age-appropriate stories that are educational and fun. Use {language_level} that's perfect for a {age}-year-old.

Incorporate themes and elements related to {interests_str} when possible, making {name} feel like the stories are made just for them.

Structure your story into clear scenes that can be visualized. Each scene should be 2-3 sentences long and paint a vivid picture.

Make the stories positive, encouraging, and help build {name}'s imagination and confidence."""

        return personalized_prompt
    
    async def set_child_system_prompt(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int,
        system_prompt: str
    ) -> bool:
        """Explicitly set a child's system prompt"""
        try:
            child = await self.get_child(db, user_id, child_id)
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                raise HTTPException(status_code=404, detail="User not found")
            
            stmt = (
                update(Child)
                .where(Child.user_id == integer_user_id)
                .where(Child.child_id == child_id)
                .values(child_prompt=system_prompt, updated_at=datetime.utcnow())  # Database field is child_prompt
            )
            
            await db.execute(stmt)
            await db.commit()
            
            print(f"✅ Updated system_prompt for child {child_id}")
            return True
            
        except HTTPException:
            raise
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to set child system_prompt: {e}")
            raise HTTPException(status_code=500, detail=f"Failed to set child system_prompt: {e}")
    
    async def set_child_voice_clone(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int,
        voice_clone_id: str
    ) -> bool:
        """Assign a voice_clone_id to the child"""
        try:
            child = await self.get_child(db, user_id, child_id)
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            # Convert firebase_user_id to integer user_id
            integer_user_id = await self._get_user_id_from_firebase_id(db, user_id)
            if not integer_user_id:
                raise HTTPException(status_code=404, detail="User not found")
            
            stmt = (
                update(Child)
                .where(Child.user_id == integer_user_id)
                .where(Child.child_id == child_id)
                .values(voice_clone_id=voice_clone_id, updated_at=datetime.utcnow())
            )
            
            await db.execute(stmt)
            await db.commit()
            
            print(f"✅ Assigned voice_clone_id {voice_clone_id} to child {child_id}")
            return True
            
        except HTTPException:
            raise
        except Exception as e:
            await db.rollback()
            print(f"❌ Failed to set child voice_clone_id: {e}")
            raise HTTPException(status_code=500, detail=f"Failed to set child voice_clone_id: {e}")
    
    async def get_child_profile_picture(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int
    ) -> Dict[str, Any]:
        """
        Get a child's profile picture information.
        
        Args:
            db: Database session
            user_id: Firebase user ID (string)
            child_id: Child ID (integer)
            
        Returns:
            Dictionary with profile picture information
        """
        try:
            # Get child profile
            child = await self.get_child(db, user_id, child_id)
            
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            has_profile_picture = child.image_url is not None and child.image_url != ""
            
            return {
                "success": True,
                "child_id": child_id,
                "image_url": child.image_url if has_profile_picture else None,
                "has_profile_picture": has_profile_picture
            }
            
        except HTTPException:
            raise
        except Exception as e:
            print(f"❌ Error getting child profile picture: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to get profile picture: {str(e)}")
    
    async def get_children_stats(
        self,
        db: AsyncSession,
        user_id: str
    ) -> Dict[str, Any]:
        """
        Get aggregated statistics across all active children for a parent.
        
        Args:
            db: Database session
            user_id: Firebase user ID (string)
            
        Returns:
            Dictionary with aggregated statistics
        """
        try:
            # Get all children
            children = await self.get_all_children(db, user_id, include_inactive=False)
            
            # Aggregate stats
            total_stories = 0
            total_voice_clones = 0
            total_reference_images = 0
            
            for child in children:
                child_stats = await self.get_child_with_stats(db, user_id, child.child_id)
                if child_stats:
                    total_stories += child_stats.story_count or 0
                    total_voice_clones += child_stats.voice_clones_count or 0
                    total_reference_images += child_stats.reference_images_count or 0
            
            stats = {
                'total_children': len(children),
                'total_stories': total_stories,
                'total_voice_clones': total_voice_clones,
                'total_reference_images': total_reference_images
            }
            
            return {"success": True, "stats": stats}
            
        except Exception as e:
            print(f"❌ Error getting children stats: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to get children stats: {str(e)}")
    
    async def get_child_stories(
        self,
        db: AsyncSession,
        user_id: str,
        child_id: int,
        limit: int = 20,
        offset: int = 0
    ) -> Dict[str, Any]:
        """
        Get all stories for a specific child.
        
        Args:
            db: Database session
            user_id: Firebase user ID (string)
            child_id: Child ID (integer)
            limit: Maximum number of stories to return
            offset: Number of stories to skip
            
        Returns:
            Dictionary with child's stories
        """
        try:
            # Verify child belongs to parent
            child = await self.get_child(db, user_id, child_id)
            if not child:
                raise HTTPException(status_code=404, detail="Child profile not found")
            
            # Import story service and query models
            from src.story.service_pg import story_service_pg
            from src.db.models.story import Story
            from src.db.models.user import User
            from sqlalchemy import select, func
            
            # Get total count
            count_stmt = (
                select(func.count(Story.story_id))
                .join(User, Story.user_id == User.user_id)
                .where(User.firebase_user_id == user_id)
                .where(Story.child_id == child_id)
            )
            count_result = await db.execute(count_stmt)
            total_count = count_result.scalar() or 0
            
            # Get stories for this child
            stories = await story_service_pg.get_user_stories(
                db=db,
                firebase_user_id=user_id,
                child_id=child_id,
                limit=limit,
                offset=offset
            )
            
            return {
                "success": True,
                "child_id": child_id,
                "child_name": child.name,
                "stories": stories if stories else [],
                "total_count": total_count,
                "has_more": (offset + len(stories)) < total_count if stories else False
            }
            
        except HTTPException:
            raise
        except Exception as e:
            print(f"❌ Error getting child stories: {str(e)}")
            raise HTTPException(status_code=500, detail=f"Failed to get child stories: {str(e)}")


# Global singleton instance
children_service = ChildrenService()

# Backward compatibility alias
child_service_pg = children_service
